### ISSUE TITLE
获取点击原图，获取的图片不清晰

### ISSUE THREAD

**Issue by zjh0667** [DennisXiaoDing/DNImagePicker#12]

**Comment by Vincentzzg** [comment]
我也在用，展示出来的相册列表真的很不清晰
请问，问题解决了吗？能不能共享下解决方法

**Comment by zjh0667** [comment]
@zhouzhongguang 
- (void)dnImagePickerController:(DNImagePickerController *)imagePickerController sendImages:(NSArray *)imageAssets isFullImage:(BOOL)fullImage
  {
  NSMutableArray *mutArr = @[].mutableCopy;
  NSMutableArray *thumbnailArr = @[].mutableCopy;
  for (DNAsset *dnasset in imageAssets) {
      ALAssetsLibrary *lib = [ALAssetsLibrary new];
      [lib assetForURL:dnasset.url resultBlock:^(ALAsset *asset){
          UIImage *image;
          if (fullImage) {
              //高清图
              image = [UIImage imageWithCGImage:asset.defaultRepresentation.fullResolutionImage];
          } else {
              image = [UIImage imageWithCGImage:asset.aspectRatioThumbnail];
          }
          [mutArr addObject:image];
          [thumbnailArr addObject:[UIImage imageWithCGImage:asset.thumbnail]];
          if (mutArr.count == imageAssets.count) {
              if (self.imgArr) {
                  self.imgArr(mutArr, thumbnailArr);
              }
          }
      } failureBlock:^(NSError *error){
  
  ```
  }];
  ```
  
  }
  }
