### ISSUE TITLE
[iOS 8+] Failed to load photos on iCloud library

### ISSUE THREAD

**Issue by darkengine** [DennisXiaoDing/DNImagePicker#19]
Failed to load photos saved on iCloud, because DNImagePicker bases on ALAssetsLibrary which doesn't support iCloud API.

因为这个库是基于ALAssetsLibrary实现的，从iOS 8+之后苹果又推出了PHPhotoLibrary，这个PHPhotoLibrary可以访问用户存储在iCloud之上的照片。所以如果是要弄新项目，建议大家换到其他库吧。

**Comment by dennisxiaoding** [comment]
[这个支持了](https://github.com/AwesomeDennis/DNImagePicker/releases/tag/V2.0)
