### ISSUE TITLE
A mistake in your code

### ISSUE THREAD

**Issue by yangoo1991** [DennisXiaoDing/DNImagePicker#2]
Thanks for your code, it helps me a lot. But I found there's a mistake in the model named "DNAsset". 
- (BOOL)isEqualToAsset:(DNAsset *)asset
  {
  if ([asset isKindOfClass:[DNAsset class]]) {
      return [asset.url isEqualToOther:asset.url]; // You must mean  [self.url isEqualToOther:asset.url];
  } else {
      return NO;
  }
  }

**Comment by dennisxiaoding** [comment]
Thanks a lot!
