### ISSUE TITLE
iOS 8.3 ＋ iPhone6X 无法获取到图片

### ISSUE THREAD

**Issue by madordie** [DennisXiaoDing/DNImagePicker#3]
不理解为什么当取出图片时候为什么要创建一个DNAsset这样的东西去暂时存储系统的ALAsset。崩溃在你取出的URL放进库里不能正常再次获取到图片。希望博主分享一下这样设计的好处。

**Comment by dennisxiaoding** [comment]
@madordie ，因为苹果api比较蛋疼，需要在ALAssetsLibrary生命周期内ALAsset才是有效的。如果出栈了，ALAssetsLibrary的对象被释放，ALAsset就失效了。所以在这里折中，传递出URL，再更具URL去获取asset

**Comment by dennisxiaoding** [comment]
@madordie 无法获取图片，是什么样的情况。我目前没有遇到，但是之前有个朋友遇到了。他说是图片的问题，但是让他把图片给我，他删了。。。。

**Comment by madordie** [comment]
并不是你描述的那样“需要在ALAssetsLibrary生命周期内ALAsset才是有效的。如果出栈了，ALAssetsLibrary的对象被释放，ALAsset就失效了。” 我测试环境iPhone6p + iOS 8.3 结果是当你获取完ALAsset的时候，把这个ALAsset的URL再放到库中，就无法正常获取到ALAsset对象，但是走的还是成功的回调。只不过这个对象为空。所以图片也就出不来了。

我目前的解决方法是在你的DNAsset增加一个属性用来保存ALAseet，为了保留原有设计，我在再次获取的时候如果为空才会使用保存的原来的这个属性。

**Comment by dennisxiaoding** [comment]
@madordie 
        The lifetimes of objects you get back from a library instance are tied to the lifetime of the library instance.
        [from](https://developer.apple.com/library/prerelease/ios/documentation/AssetsLibrary/Reference/ALAssetsLibrary_Class/index.html#//apple_ref/occ/cl/ALAssetsLibrary)

根据官方文档，你保存ALAsset并不保险，就是遇到过，传递出ALAsset对象，在获取图片的时候，ALAssetsLibrary对象释放，导致收到警告，才加了这一层DNAsset，传递出URL再去获取Asset。
可能我们说的情况存在差异，你在根据asset的url获取asset的时候返回的是nil。目前遇到过的有两种情况
1. 获取照片流相册里的图片，解决方法，Demo有说明，
2.就是我上面回复的，是图片的问题。但是没亲自遇到并且解决过
