### ISSUE TITLE
可以考虑为DNAsset 添加一个属性image

### ISSUE THREAD

**Issue by RondaHo** [DennisXiaoDing/DNImagePicker#5]
像JKImagePicker那样，asset有一个image属性，感觉这样更方便。
感谢作者开源，已经80%的仿微信了，除了相册照片太多后预览滑动性能稍差，其他都非常不错

**Comment by dennisxiaoding** [comment]
@heyehao2008 如果原图加载进image，内存太大了

**Comment by RondaHe** [comment]
嗯，也有这方面的原因，谢谢作者开源，我自己再优化一下

**Comment by dennisxiaoding** [comment]
@heyehao2008 ,一起努力，感谢
