### ISSUE TITLE
2个小问题

### ISSUE THREAD

**Issue by guanghua07** [DennisXiaoDing/DNImagePicker#6]
我发现有两个小问题
1.从相册选择里选择图片，当图片过多的时候 显示不全，系统是IOS8.4.1，设备是iphone5s。
2.如果导入MWPhotobrowse 库后，会与你这个DNImagePicker冲突，要删除MWTapDetectingImageView才可以编译通过。

**Comment by dennisxiaoding** [comment]
第二个问题我改了一下类名，之前疏忽了。
第一个问题我这边不好复现
