### ISSUE TITLE
大量图片不能完全展示

### ISSUE THREAD

**Issue by MrMarik** [DennisXiaoDing/DNImagePicker#7]
图片很多时候最后一行的图片会被遮挡小部分，
修改了CollectionView的Y之后正常

**Comment by dennisxiaoding** [comment]
@MrMarik 是在查看相册图片的部分吗

**Comment by MrMarik** [comment]
是的，DNImageFlowViewController下面的imageFlowCollectionView

**Comment by jiangyancong** [comment]
@MrMarik 能不能提一个PR或者fork一个修复之后的分支出来？
