### ISSUE TITLE
xcode7.2 4s模拟器，iOS9.2系统，从列表进入collectionView直接崩溃 

### ISSUE THREAD

**Issue by Daren-Wang** [DennisXiaoDing/DNImagePicker#8]
**\* Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 0; nan 480]'
**\* First throw call stack:
(
    0   CoreFoundation                      0x0332fa14 **exceptionPreprocess + 180
    1   libobjc.A.dylib                     0x02a4fe02 objc_exception_throw + 50
    2   CoreFoundation                      0x0332f93d +[NSException raise:format:] + 141
    3   QuartzCore                          0x01148f06 _ZN2CA5Layer10set_boundsERKNS_4RectEb + 260
    4   QuartzCore                          0x0114919e -[CALayer setBounds:] + 136
    5   UIKit                               0x01456153 -[UIView _createLayerWithFrame:] + 754
    6   UIKit                               0x01456837 UIViewCommonInitWithFrame + 830
    7   UIKit                               0x01456485 -[UIView initWithFrame:] + 138
    8   UIKit                               0x0148c6b3 -[UIScrollView initWithFrame:] + 73
    9   UIKit                               0x01d131b9 -[UICollectionView initWithFrame:collectionViewLayout:] + 144
    10  DHCMApp                             0x0004f789 -[DNImageFlowViewController imageFlowCollectionView] + 569
    11  DHCMApp                             0x0004d31a -[DNImageFlowViewController setupView] + 554
    12  DHCMApp                             0x0004ca78 -[DNImageFlowViewController viewDidLoad] + 88
    13  UIKit                               0x0157e2ae -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 44
    14  UIKit                               0x01582dce -[UIViewController loadViewIfRequired] + 1384
    15  UIKit                               0x01589406 -[UIViewController __viewWillAppear:] + 114
    16  UIKit                               0x015ac5b9 -[UIViewController(UIContainerViewControllerProtectedMethods) beginAppearanceTransition:animated:] + 202
    17  UIKit                               0x015be9cc -[UINavigationController _startCustomTransition:] + 1389
    18  UIKit                               0x015d0769 -[UINavigationController _startDeferredTransitionIfNeeded:] + 803
    19  UIKit                               0x015d1ada -[UINavigationController __viewWillLayoutSubviews] + 68
    20  UIKit                               0x017adc4a -[UILayoutContainerView layoutSubviews] + 252
    21  UIKit                               0x01483008 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 810
    22  libobjc.A.dylib                     0x02a64059 -[NSObject performSelector:withObject:] + 70
    23  QuartzCore                          0x0115280a -[CALayer layoutSublayers] + 144
    24  QuartzCore                          0x011464ee _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 388
    25  QuartzCore                          0x01146352 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 26
    26  QuartzCore                          0x01138e8b _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 317
    27  QuartzCore                          0x0116ce03 _ZN2CA11Transaction6commitEv + 561
    28  QuartzCore                          0x0116e674 _ZN2CA11Transaction17flush_transactionEv + 50
    29  UIKit                               0x013e7dfa _afterCACommitHandler + 197
    30  CoreFoundation                      0x03248ffe __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION** + 30
    31  CoreFoundation                      0x03248f5e __CFRunLoopDoObservers + 398
    32  CoreFoundation                      0x0323e8dc __CFRunLoopRun + 1340
    33  CoreFoundation                      0x0323e0e6 CFRunLoopRunSpecific + 470
    34  CoreFoundation                      0x0323defb CFRunLoopRunInMode + 123
    35  GraphicsServices                    0x0566a664 GSEventRunModal + 192
    36  GraphicsServices                    0x0566a4a1 GSEventRun + 104
    37  UIKit                               0x013b6bfa UIApplicationMain + 160
    38  DHCMApp                             0x000ceaba main + 138
    39  libdyld.dylib                       0x03d54a21 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dennisxiaoding** [comment]
@nanmingzhidian 目前看来是初始化collectionView的frame的时候，width不是个合法的float值。
